% 用原始图像 lena.bmp 或 cameraman.bmp 分别加产生的 3%椒盐噪声、高斯噪声、随机噪声合成有噪声的图像并显示；
% 用均值滤波器去除图像中的噪声（选 3x3 窗口）
pic = imread('lena.bmp');
pic = rgb2gray(pic);
pic = im2double(pic);
pic1 = imnoise(pic,'salt & pepper',0.03);
pic2 = imnoise(pic,'gaussian',0,0.03);
pic3 = imnoise(pic,'speckle',0.03);
pic1 = im2double(pic1);
pic2 = im2double(pic2);
pic3 = im2double(pic3);
pic1 = medfilt2(pic1,[3,3]);
pic2 = medfilt2(pic2,[3,3]);
pic3 = medfilt2(pic3,[3,3]);
subplot(2,2,1);
imshow(pic);
title('原始图像');
subplot(2,2,2);
imshow(pic1);
title('椒盐噪声');
subplot(2,2,3);
imshow(pic2);
title('高斯噪声');
subplot(2,2,4);
imshow(pic3);
title('随机噪声');
% 用中值滤波器去除图像中的噪声（选 3x3 窗口）
% 用高斯滤波器去除图像中的噪声（选 3x3 窗口）
pic1 = imnoise(pic,'salt & pepper',0.03);
pic2 = imnoise(pic,'gaussian',0,0.03);
pic3 = imnoise(pic,'speckle',0.03);
pic1 = im2double(pic1);
pic2 = im2double(pic2);
pic3 = im2double(pic3);
pic1 = imgaussfilt(pic1,1);
pic2 = imgaussfilt(pic2,1);
pic3 = imgaussfilt(pic3,1);
subplot(2,2,1);
imshow(pic);
title('原始图像');
subplot(2,2,2);
imshow(pic1);
title('椒盐噪声');
subplot(2,2,3);
imshow(pic2);
title('高斯噪声');
subplot(2,2,4);
imshow(pic3);
title('随机噪声');
% 用自适应中值滤波器去除图像中的噪声（选 3x3 窗口）
pic1 = imnoise(pic,'salt & pepper',0.03);
pic2 = imnoise(pic,'gaussian',0,0.03);
pic3 = imnoise(pic,'speckle',0.03);
pic1 = im2double(pic1);
pic2 = im2double(pic2);
pic3 = im2double(pic3);
pic1 = adpmedian(pic1,3);
pic2 = adpmedian(pic2,3);
pic3 = adpmedian(pic3,3);
subplot(2,2,1);
imshow(pic);
title('原始图像');
subplot(2,2,2);
imshow(pic1);
title('椒盐噪声');
subplot(2,2,3);
imshow(pic2);
title('高斯噪声');
subplot(2,2,4);
imshow(pic3);
title('随机噪声');
